### ISSUE TITLE
Does not work in Action context

### ISSUE THREAD

**Issue by blackfyre** [royduin/laravel-nova-field-dynamic-select#12]
I'm currently trying to replace the MorphTo field in the action context, since that doesn't work, but for some reason, this fails as well.

The error message I get is: `Call to a member function getOptions() on null`

**Comment by royduin** [comment]
Not sure, I didn't use it like that. If you manage to fix it a pull request is welcome.

**Comment by subzero10** [comment]
I just came across this package and needed it in Nova Actions, here is a PR that works for me: https://github.com/royduin/laravel-nova-field-dynamic-select/pull/13

**Comment by royduin** [comment]
@subzero10 fixed it @blackfyre 🚀

**Comment by blackfyre** [comment]
Wow! Great! Thanks @subzero10 !
