### ISSUE TITLE
it doesn't install 

### ISSUE THREAD

**Issue by manafn** [royduin/laravel-nova-field-dynamic-select#21]
**No publishable resources for tag [laravel-assets]. and I can't find the folder of the package**

`PS C:\Users\Manaf\Desktop\New folder\nofa> composer require royduin/laravel-nova-field-dynamic-select
Using version ^1.8 for royduin/laravel-nova-field-dynamic-select
./composer.json has been updated
Running composer update royduin/laravel-nova-field-dynamic-select
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking royduin/laravel-nova-field-dynamic-select (1.8.4)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading royduin/laravel-nova-field-dynamic-select (1.8.4)
  - Installing royduin/laravel-nova-field-dynamic-select (1.8.4): Extracting archive
Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: digital-creative/clickable-table-row
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: laravel/nova
Discovered Package: laravel/sail
Discovered Package: laravel/tinker
Discovered Package: laravel/ui
Discovered Package: manmohanjit/nova-belongs-to-dependency
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: orlyapps/nova-belongsto-depend
Discovered Package: royduin/laravel-nova-field-dynamic-select
Discovered Package: webparking/nova-belongs-to-dependency
Package manifest generated successfully.
83 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> @php artisan vendor:publish --tag=laravel-assets --ansi
No publishable resources for tag [laravel-assets].
Publishing complete.`

**Comment by royduin** [comment]
I don't see anything wrong here? There are no publishable resources...

**Comment by manafn** [comment]
what do you think the problem ? when I add like 
use Manmohanjit\BelongsToDependency\BelongsToDependency;
it can't find it , I faced this problem with multiple packages like thais.

**Comment by royduin** [comment]
That's another package? Did you see the example: https://github.com/royduin/laravel-nova-field-dynamic-select#example and import this one:
```
use Hubertnnn\LaravelNova\Fields\DynamicSelect;
```

**Comment by manafn** [comment]
it says class Hubertnnn\LaravelNova\Fields\DynamicSelect not fount

**Comment by royduin** [comment]
Sorry, it should be:
```
use Hubertnnn\LaravelNova\Fields\DynamicSelect\DynamicSelect;
```

**Comment by manafn** [comment]
worked thank you very much , another question can I use it like this :
class has many sections and secition has many students

so I want it to show only sections of the selected class in the first dropdown, depending on the realtion not the options I write  ?

**Comment by royduin** [comment]
That's possible, here is an example:

```
DynamicSelect::make('Maingroup', 'maingroup_id')
    ->options(function () {
        return Maingroup::pluck('name', 'id');
    }),
DynamicSelect::make('Articlegroup', 'articlegroup_id')
    ->dependsOn(['maingroup_id'])
    ->options(function ($values) {
        if ($values['maingroup_id']) {
            return Maingroup::find($values['maingroup_id'])->articlegroups->pluck('name', 'id');
        }

        return [];
    }),
```
