### ISSUE TITLE
Changing placeholders values

### ISSUE THREAD

**Issue by fredrikmikkelsen** [royduin/laravel-nova-field-dynamic-select#3]
Is it possible to change the Select's placeholders? Such as the "Pick a value" and "Press enter to select":

![image](https://user-images.githubusercontent.com/70882158/101364333-bbb52380-38a2-11eb-8175-0509d9d068e3.png) 

![image](https://user-images.githubusercontent.com/70882158/101364461-e43d1d80-38a2-11eb-9ba3-0e6951827107.png)

**Comment by royduin** [comment]
Currently not; but it's not that hard to implement. All props with the labels can be found here: https://vue-multiselect.js.org/#sub-props. Add them to the meta with `__()` to make them translatable in `DynamicSelect.php`. After that you can use them in the `FormField.vue` with for example: `:placeholder="field.placeholder"`. Lastly `yarn && yarn run prod` and create a pull request.

**Comment by fredrikmikkelsen** [comment]
Thank you for the quick answer. Where in the meta should it be added?

**Comment by royduin** [comment]
In the array just like the other options.

**Comment by royduin** [comment]
Fixed in #4
