### ISSUE TITLE
Namespace not found?

### ISSUE THREAD

**Issue by Alrektii** [royduin/laravel-nova-field-dynamic-select#5]
Hi,

Whenever I download the package and put in the namespace for the dynamicselect I get this error:
![image](https://user-images.githubusercontent.com/29793158/101890731-611d0f80-3ba1-11eb-875e-b1084b42aa28.png)

Namespace im using is : use Royduin\LaravelNovaFieldDynamicSelect\DynamicSelect;

Nova version: 2.9.4

**Comment by royduin** [comment]
The namespace is `Hubertnnn\LaravelNova\Fields\DynamicSelect`

**Comment by Alrektii** [comment]
![image](https://user-images.githubusercontent.com/29793158/101891673-a7bf3980-3ba2-11eb-9156-6cb952d6f036.png)
No luck :(

**Comment by royduin** [comment]
The namespace is `Hubertnnn\LaravelNova\Fields\DynamicSelect` so you've to import `Hubertnnn\LaravelNova\Fields\DynamicSelect\DynamicSelect`

**Comment by Alrektii** [comment]
that was it thanks

**Comment by Epizefiri** [comment]
> Hubertnnn\LaravelNova\Fields\DynamicSelect

please add this info in the readme file!
